name: Create Release

on:
  push:
    tags:
      - v*
      - pre-rel-*

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - windows

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
    - name: Collect binaries
      run: dotnet run --project Golem.Package --configuration Release build

    - name: Pack
      id: pack
      shell: bash
      env:
        OS_NAME: ${{ matrix.os }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        bash .ci/pack-build.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          releases/gamerhash-ai-facade-*
        prerelease: ${{ startsWith(github.ref, 'refs/tags/pre-rel-v') }}
