name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - windows

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test -v diag
    - name: Archive JobTests artifacts
      uses: actions/upload-artifact@v3
      with:
        name: JobTests
        path: |
          Golem.Tests/tests/JobTests/modules/golem-data/yagna/*.log
          Golem.Tests/tests/JobTests/modules/golem-data/provider/*.log
    - name: Archive JobTests requestor artifacts
      uses: actions/upload-artifact@v3
      with:
        name: JobTests_requestor
        path: |
          Golem.Tests/tests/JobTests_requestor/modules/golem-data/yagna/*.log
